Linking to new LS docs and New to Omics
arcus/Arcus_Labs_Orientation pull request #47
Opened 2023-11-03 13:57 UTC by pm0kjp

@leemc-data-ed and @allrolsen and @nafeldman can you take a peek at the changes here?  I'm linking to New to Omics and the LS documents from the main Arcus Lab Orientation.

2023-11-03 14:09 UTC, allrolsen commented
> @leemc-data-ed and @allrolsen and @nafeldman can you take a peek at the changes here? I'm linking to New to Omics and the LS documents from the main Arcus Lab Orientation.

Thank you for adding links to our LS modules. I think the copy looks good!

2023-11-03 14:19 UTC, leemc-data-ed requested changes
Just one small suggestion, but otherwise this looks good to me!

2023-11-03 14:19 UTC, leemc-data-ed commented on arcus_orientation.md
> +- **[New to Omics](https://liascript.github.io/course/?https://raw.githubusercontent.com/arcus/Arcus_Labs_Orientation/main/new_to_omics.md#1)** will get you started if you're using the Arcus Omics Tr
The wording here seems a bit repetitive, maybe something like this? 
```suggestion
- **[New to Omics](https://liascript.github.io/course/?https://raw.githubusercontent.com/arcus/Arcus_Labs_Orientation/main/new_to_omics.md#1)** will get you started if you're using the Arcus Omics Training Lab. The instructions in this document presuppose that specific files, containing pre-defined data, exist and that you're working in the Omics Training Lab.
```

2023-11-06 13:51 UTC, nafeldman commented
looks awesome, thank you both!

2023-11-06 14:32 UTC, leemc-data-ed approved these changes
Lgtm!

2023-11-06 14:32 UTC, merged